In [2]:
import pandas as pd
import re

In [3]:
poli = pd.read_csv('./data/chosun_poli_commonword.csv', sep=(','), encoding='utf-8')
eco = pd.read_csv('./data/chosun_eco_commonword.csv', sep=(','), encoding ='utf-8')
soci = pd.read_csv('./data/chosun_social_commonword.csv', sep=(','), encoding='utf-8')
opi = pd.read_csv('./data/chosun_opinion_commonword.csv', sep=(','), encoding='utf-8')

#### 데이터프레임화

In [4]:
poli_df = pd.DataFrame(poli)
eco_df = pd.DataFrame(eco)
soci_df = pd.DataFrame(soci)
opi_df = pd.DataFrame(opi)

#### 불필요한 열 제거

In [5]:
poli_df.drop('Unnamed: 0',axis=1, inplace=True)
eco_df.drop('Unnamed: 0',axis=1, inplace=True)
soci_df.drop('Unnamed: 0',axis=1, inplace=True)
opi_df.drop('Unnamed: 0',axis=1, inplace=True)

#### 컬럼 명 변경

In [6]:
poli_df.rename(columns={'단어명':'단어명', '빈도수':'정치빈도수'}, inplace=True)
eco_df.rename(columns={'단어명':'단어명', '빈도수':'경제빈도수'}, inplace=True)
soci_df.rename(columns={'단어명':'단어명', '빈도수':'사회빈도수'}, inplace=True)
opi_df.rename(columns={'단어명':'단어명', '빈도수':'사설빈도수'}, inplace=True)

#### '단어명' 기준으로 병합

In [7]:
from functools import reduce
import pandas as pd
dfs = [poli_df, eco_df, soci_df, opi_df]
df_merge = reduce(lambda left, right: pd.merge(left, right, on='단어명'), dfs)

In [8]:
df_merge[:50]

     단어명  정치빈도수  경제빈도수  사회빈도수  사설빈도수
0    대통령   1433    117    241    154
1    김정은    682     10     33    114
2     한국    655   1305    434    141
3      것    545    674    229     97
4     남북    501    105     29     45
5     회담    494     23      7     37
6     정부    417    641    154    159
7    비핵화    370      6      6     45
8    트럼프    362     96     18     68
9     후보    302     75     58     23
10  정상회담    288     39      9     51
11    국회    284     48     38     11
12     명    284    568    837     28
13    북한    270     50     41     52
14    선언    259     28     11     25
15    대표    251    427    103     18
16    평양    230     11     20     19
17    속보    225     23    375      1
18   민주당    222      5     18      8
19     단    219     74     34     16
20    제재    218     56      3     32
21    합의    206     98     29     15
22     안    205    237    187     94
23    평화    200      9     15     23
24    장관    197    176     61     30
25    한미    196     92      7      7
26     등    194    799    288     11
27     북    192     27     13     30
28     위    187    651    122     38
29    훈련    186      8     24     21
30   김성태    183      3     21      1
31    의원    181     46    104     31
32    논의    180     95     16     10
33   판문점    180      1      4      8
34  지방선거    177     16     14      9
35    대북    176     16      8     29
36     중    173    493    214     34
37    드루    171      6    250     30
38     킹    171     14    253     30
39    추진    167    290     34     14
40    경제    166    489     24     67
41    논란    162    202    198     13
42     전    154    298    389     30
43   한반도    153     15     36     26
44    대화    151     39     12     27
45     핵    144      4      4     34
46    오늘    142    194    755     10
47    문제    141    106     69     27
48    미래    140    267    142     20
49    선거    139     37     23     25

In [25]:
df_merge['총빈도수']=df_merge.sum(axis=1)
df_merge[:30]

      단어명  정치빈도수  경제빈도수  사회빈도수  사설빈도수   총빈도수
2      한국    655   1305    434    141  10140
0     대통령   1433    117    241    154   7780
12      명    284    568    837     28   6868
864    삼성     15   1418    139     12   6336
3       것    545    674    229     97   6180
904     외     14    278    816    338   5784
6      정부    417    641    154    159   5484
26      등    194    799    288     11   5168
670    투자     20   1159     27     14   4880
46     오늘    142    194    755     10   4404
273    기업     47    952     52     40   4364
28      위    187    651    122     38   3992
526    회장     26    716    236      7   3940
1545   전자      6    927     41      4   3912
1558   금융      6    925     20      8   3836
80     서울    112    449    348     17   3704
1023   영업     12    894     14      3   3692
36      중    173    493    214     34   3656
241     주     51    782     54      6   3572
54     인사    138    434    289     12   3492
42      전    154    298    389     30   3484
93      더    103    430    276     48   3428
1     김정은    682     10     33    114   3356
295    시장     44    710     43     17   3256
15     대표    251    427    103     18   3196
309    사업     41    684     33     17   3100
147     개     73    504    150     20   2988
40     경제    166    489     24     67   2984
265    경찰     48     17    644     24   2932
22      안    205    237    187     94   2892

In [26]:
df_merge=df_merge.sort_values(by="총빈도수", ascending = False)
df_merge[:50]

      단어명  정치빈도수  경제빈도수  사회빈도수  사설빈도수   총빈도수
2      한국    655   1305    434    141  10140
0     대통령   1433    117    241    154   7780
12      명    284    568    837     28   6868
864    삼성     15   1418    139     12   6336
3       것    545    674    229     97   6180
904     외     14    278    816    338   5784
6      정부    417    641    154    159   5484
26      등    194    799    288     11   5168
670    투자     20   1159     27     14   4880
46     오늘    142    194    755     10   4404
273    기업     47    952     52     40   4364
28      위    187    651    122     38   3992
526    회장     26    716    236      7   3940
1545   전자      6    927     41      4   3912
1558   금융      6    925     20      8   3836
80     서울    112    449    348     17   3704
1023   영업     12    894     14      3   3692
36      중    173    493    214     34   3656
241     주     51    782     54      6   3572
54     인사    138    434    289     12   3492
42      전    154    298    389     30   3484
93      더    103    430    276     48   3428
1     김정은    682     10     33    114   3356
295    시장     44    710     43     17   3256
15     대표    251    427    103     18   3196
309    사업     41    684     33     17   3100
147     개     73    504    150     20   2988
40     경제    166    489     24     67   2984
265    경찰     48     17    644     24   2932
22      안    205    237    187     94   2892
66      첫    124    396    187     11   2872
590    개발     23    644     29      9   2820
1668    년      5    688      5      6   2816
144     제     73    492    111     26   2808
70     지원    118    495     78      9   2800
426    최대     32    604     56      8   2800
175    검찰     65     64    550     16   2780
4      남북    501    105     29     45   2720
1514   증가      6    653      5      3   2668
64      차    126    401    107     28   2648
120    중국     84    459     55     55   2612
413    올해     33    550     62      3   2592
2668   현대      1    627     13      2   2572
78     개최    112    353    169      3   2548
17     속보    225     23    375      1   2496
611    국내     22    536     59      4   2484
104    공개     95    373    123     17   2432
2843   롯데      1    582     23      1   2428
62     의혹    128     54    405      8   2380
988    기술     12    533     35     10   2360

In [8]:
df_merge.to_csv('./word_freq_df.csv', sep=(','), encoding='utf-8')